var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "networks": "",
    "performance": "",
    "display": "",
    "rearcamera": "",
    "frontcamera": "",
    "battery": "",
    "memory": "",
    "rom": "",
    "disc":"",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
}, {
    "id": 1,
    "title": "Apple iphone 15",
    "price": 79900,
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 17, upgradable to iOS 17.0.3",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 1000 nits (HBM), 2000 nits (peak)",
    "rearcamera": "48 MP, f/1.6, 26mm (wide), 1/1.56, 1.0µm dual pixel PDAF sensor shift OIS",
    "frontcamera": "12 MP, f/1.9, 23mm (wide), 1/3.6",
    "battery": "Li-Ion 3349 mAh, non-removable",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg"
}, {
    
    "id": 2,
    "title": "Apple iPhone 14",
    "price": "61999",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 16, upgradable to iOS 17.0.3",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "rearcamera": "12 MP, f/1.5, 26mm (wide), 1/1.7' 1.9µm, dual pixel PDAF, sensor-shift OIS",
    "frontcamera": "12 MP, f/1.9, 23mm (wide), 1/3.6",
    "battery": "Li-Ion 3279 mAh, non-removable (12.68 Wh)",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"Stay productive and improve your performance with the Super Retina XDR display that is comfortable for the eyes. Powered with a 12 MP main camera, enjoy taking pictures with friends and family. With a built-in rechargeable lithium-ion battery and equipped with the MagSafe wireless charging, you can charge your phone quickly up to 50 % in just half an hour by using a 20 W adapter. This phone is loaded with a horde of exciting features such as Siri, face ID, barometer, ambient light sensors etc., and is also resistant to dust and water as it is IP68 rated.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg"
}, {
    "id": 3,
    
    "title": "Apple iPhone 13",
    "price": "47999",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 15, upgradable to iOS 17.0.3",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "rearcamera": "12 MP, f/1.6, 26mm (wide), 1.7µm, dual pixel PDAF, sensor-shift OIS 12 MP f/2.4, 120˚ 13mm (ultrawide)",
    "frontcamera": "12 MP, f/2.2, 23mm (wide), 1/3.6' SL 3D (depth/biometrics sensor)",
    "battery": "Li-Ion 3240 mAh, non-removable (12.41 Wh)",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg"
}, {
    "id": 4,
    "title": "Apple iPhone 12",
    "price": "48990",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 14.1, upgradable to iOS 17.0.3",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 625 nits (HBM), 1200 nits (peak)",
    "rearcamera": "12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS",
    "frontcamera": "12 MP, f/2.2, 23mm (wide), 1/3.6'SL 3D, (depth/biometrics sensor)",
    "battery": "Li-Ion 2815 mAh, non-removable (10.78 Wh)",
    "memory": "64gb",
    "rom": "4gb",
    "disc":"Dive into a world of crystal-clear visuals with this iPhone’s Super Retina XDR Display. This beast of a smartphone packs the A14 Bionic chip to make for blazing-fast performance speeds. On top of that, its Dual-camera System, along with Night Mode, helps you click amazing pictures and selfies even when the lighting isn’t as good as you’d want it to be.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg"
}, {
    "id": 5,
    "title": "Apple iPhone 11",
    "price": "36990",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE",
    "performance": "iOS 13, upgradable to iOS 17.0.3",
    "display": "Liquid Retina IPS LCD, 625 nits (typ)",
    "rearcamera": "12 MP, f/1.8, 26mm (wide), 1/2.55, 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6",
    "frontcamera": "12 MP, f/2.2, 23mm (wide), 1/3.6'SL 3D, (depth/biometrics sensor)",
    "battery": "Li-Ion 3110 mAh, non-removable (11.91 Wh)		Charging	Wired, PD2.0, 50% in 30 min (advertised)Wireless (Qi)",
    "memory": "64gb",
    "rom": "4gb",
    "disc":"The iPhone 11 boasts a gorgeous all-screen Liquid Retina LCD that is water resistant up to 2 metres for up to 30 minutes. Moreover, the ultra-wide 13 mm lens has a 120-degree field of view for four times more scenes, and the 26 mm wide lens provides up to 100% Autofocus in low light.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11.jpg"
}, {
    "id": 6,
    "title": "Apple iPhone 11 Pro",
    "price": "1,06,600",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE",
    "performance": "iOS 13, upgradable to iOS 17.0.3 Apple A13 Bionic (7 nm+) ",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak) 5.8 inches, 84.4 cm2 (~82.1% screen-to-body ratio)",
    "rearcamera": "12 MP, f/1.8, 26mm (wide), 1/2.55', 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.0, 52mm (telephoto), 1/3.4', 1.0µm, PDAF, OIS, 2x optical zoom12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6",
    "frontcamera": "12 MP, f/2.2, 23mm (wide), 1/3.6' SL 3D, (depth/biometrics sensor)",
    "battery": "Li-Ion 3046 mAh, non-removable (11.67 Wh) Wired, PD2.0, 50% in 30 min (advertised) Wireless (Qi)",
    "memory": "64gb",
    "rom": "4gb",
    "disc":"The iPhone 11 Pro features Triple 12 MP Ultra Wide (13mm), Wide (26mm) and Telephoto (52mm) cameras. The Ultra wide camera provides 120° field of view, letting you capture four times more scene, and the wide camera provides 100% Focus Pixels and Optical image stabilisation and the telephoto camera comes with an f/2.0 aperture and 2x optical zoom.",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max-.jpg"
}, {
    "id": 7,
    "title": "Apple iPhone 12 Pro",
    "price": "78,899",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 14.1, upgradable to iOS 17.0.3 Apple A14 Bionic (5 nm)",
    "display": "Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio) ",
    "rearcamera": "12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS12 MP, f/2.0, 52mm (telephoto), 1/3.4', 1.0µm, PDAF, OIS, 2x optical zoom12 MP, f/2.4, 13mm, 120˚ (ultrawide), 1/3.6'TOF 3D LiDAR scanner (depth)",
    "frontcamera": "12 MP, f/2.2, 23mm (wide), 1/3.6' SL 3D, (depth/biometrics sensor)",
    "battery": "Li-Ion 2815 mAh, non-removable (10.78 Wh)",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"   Splash, Water and Dust Resistant (Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529), Ceramic Shield Front, Aerospace-grade Aluminium, Compatible with MagSafe Accessories and Wireless Chargers, Audio Playback: Spatial Audio Playback, Supports Dolby Atmos, Video Playback: HDR with Dolby Vision, HDR10 and HLG",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro--.jpg"
}, {
    "id": 8,
    "title": "Apple iPhone 13 pro ",
    "price": "74,999",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 15, upgradable to iOS 17.0.3 Apple A15 Bionic (5 nm)",
    "display": "6.1-inch (15.5 cm diagonal) Super Retina XDR display with True Tone",
    "rearcamera": "Dual 12MP cameras with Portrait mode, Depth Control, Portrait Lighting, Smart HDR, and 4K Dolby Vision HDR video up to 30 fps",
    "frontcamera": "12MP TrueDepth front camera with Portrait mode, Depth Control, Portrait Lighting, and Smart HDR 4",
    "battery": "Video playback:Up to 19 hours, Video playback (streamed):Up to 15 hours, Audio playback:Up to 75 hours, 20W adapter or higher (sold separately), Fast-charge capable: Up to 50% charge in around 30 minutes with 20W adapter or higher",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"15 cm (6.1-inch) Super Retina XDR display Cinematic mode adds shallow depth of field and shifts focus automatically in your videos Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording 12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording A15 Bionic chip for lightning-fast performance",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg"
}, {
    "id": 9,
    "title": "Apple iPhone 14 Pro ",
    "price": "1,19,990",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "	iOS 16, upgradable to iOS 17.0.3 Apple A16 Bionic (4 nm) Hexa-core (2x3.46 GHz Everest + 4x2.02 GHz Sawtooth)", 
    "display": "6.1-inchSuper Retina XDR display with ProMotion",
    "rearcamera": "Pro camera system: 48MP Main, 12MP Ultrawide, and 12MP 2x Telephoto with Portrait mode, Depth Control, Portrait Lighting, Smart HDR 4, and 4K Dolby Vision HDR video up to 60 fps",
    "frontcamera": "12MP TrueDepth front camera with Portrait mode, Depth Control, Portrait Lighting, and Smart HDR 4",
    "battery": "Video playback: Up to 23 hours Video playback (streamed): Up to 20 hours Audio playback: Up to 75 hours 20W adapter or higher (sold separately) Fast-charge capable:Up to 50% charge in around 30 minutes with 20W adapter or higher (available separately",
    "memory": "128gb",
    "rom": "6gb",
    "disc":"15.54 cm (6.1-inch) Super Retina XDR display featuring Always-On and ProMotionDynamic Island, a magical new way to interact with iPhone48MP Main camera for up to 4x greater resolutionCinematic mode now in 4K Dolby Vision up to 30 fpsAction mode for smooth, steady, handheld videosAll-day battery life and up to 23 hours of video playback",
    "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg"
}, {
    "id": 10,
    "title": "Apple iPhone 15 Pro",
    "price": "1,34,900",
    "networks": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
    "performance": "iOS 17, upgradable to iOS 17.0.3 Apple A17 Pro (3 nm) Hexa-core (2x3.78 GHz + 4x2.11 GHz) Apple GPU (6-core graphics)",
    "display": "LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM) 6.1 inches, 91.3 cm2 (~88.2% screen-to-body ratio) 1179 x 2556 pixels, 19.5:9 ratio (~461 ppi density) Always-On display",
    "rearcamera": "48 MP, f/1.8, 24mm (wide), 1/1.28', 1.22µm, dual pixel PDAF, sensor-shift OIS12 MP, f/2.8, 77mm (telephoto), 1/3.5', 1.0µm, PDAF, OIS, 3x optical zoom12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55', 1.4µm, dual pixel PDAFTOF 3D LiDAR scanner (depth)",
    "frontcamera": "12 MP, f/1.9, 23mm (wide), 1/3.6', PDAF, OIS SL 3D, (depth/biometrics sensor)HDR, Cinematic mode (4K@24/30fps) ",
    "battery": "Li-Ion 3274 mAh, non-removable Wired, 50% in 30 min (advertised)15W wireless (MagSafe)7.5W wireless (Qi)4.5W reverse wired",
    "memory": "128gb",
    "rom": "8gb",
    "disc":"iPhone 15 Pro, a titanium marvel, boasts an aerospace-grade build, making it the lightest Pro model ever. The A17 Pro Chip marks a historic leap in Apple GPUs, delivering unparalleled graphics performance and immersive gaming experiences. The camera system shines with a 48MP Main camera, offering remarkable detail and automatic portrait enhancements. Convenience is key with the Action button for quick tasks and Focus filters. Plus, it's USB 3 compatible, revolutionizing data transfer speeds. This iPhone even shares its charging cable with your Mac or iPad. Embrace innovation, cut cable clutter, and elevate your mobile experience with the iPhone 15 Pro.",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/0/q/d/-original-imagtc4hzawdcp4g.jpeg?q=70"
}]